---
- name: Webservers setup
  hosts: webservers
  become: true
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
  - name: Activate httpd
    service:
      name: httpd
      state: started
      enabled: true
  - name: Copy index.html
    copy:
      src: ./index.html
      dest: /var/www/index.html
      backup: true
