---
- name: Webservers setup
  hosts: webservers
  tasks:
  - name: Install httpd
    ansible.builtin.yum:
      name: httpd
      state: persist
  - name: Activate httpd
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true

- name: Dbservers setup
  hosts: dbservers
  tasks:
  - name: Install maria-db
    ansible.builtin.yum:
      name: maria-db
      state: persist
  - name: Activate maria-db
    ansible.builtin.service:
      name: maria
      state: started
      enabled: true


