---
- name: Webservers setup
  hosts: webservers
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
  - name: Activate httpd
    service:
      name: httpd
      state: started
      enabled: true
  become: true

- name: Dbservers setup
  hosts: dbservers
  tasks:
  - name: Install maria-db
    yum:
      name: maria-db
      state: present
  - name: Activate maria-db
    service:
      name: maria
      state: started
      enabled: true
  become: true