---
- name: Webservers setup
  hosts: webservers
  become: true
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
  - name: Activate httpd
    service:
      name: httpd
      state: started
      enabled: true


- name: Dbservers setup
  hosts: dbservers
  become: true
  tasks:
  - name: Install mariadb
    yum:
      name: mariadb-server
      state: present
  - name: Activate mariadb
    service:
      name: mariadb
      state: started
      enabled: true
